### ISSUE TITLE
Updating to last angular version 2.4.3

### ISSUE THREAD

**Issue by piermorosini** [ligershark/CoreTemplatePack#25]
### Installed product versions
- Visual Studio: 2015 Enterprise
- This extension:  1.1.37

### Description
Error after updating to last angular version 2.4.3

### Steps to recreate
ncu -u

New package version
    "@angular/common": "2.4.3",
    "@angular/compiler": "2.4.3",
    "@angular/core": "2.4.3",
    "@angular/forms": "2.4.3",
    "@angular/http": "2.4.3",
    "@angular/platform-browser": "2.4.3",
    "@angular/platform-browser-dynamic": "2.4.3",
    "@angular/platform-server": "2.4.3",
    "@angular/router": "3.4.3",
    "@types/node": "^7.0.0",
    "angular2-platform-node": "~2.1.0-rc.1",
    "angular2-universal": "~2.1.0-rc.1",
    "angular2-universal-polyfills": "~2.1.0-rc.1",
    "aspnet-prerendering": "^2.0.2",
    "aspnet-webpack": "^1.0.11",
    "bootstrap": "^3.3.7",
    "css": "^2.2.1",
    "css-loader": "^0.26.1",
    "es6-shim": "^0.35.1",
    "expose-loader": "^0.7.1",
    "extract-text-webpack-plugin": "^1.0.1",
    "file-loader": "^0.9.0",
    "isomorphic-fetch": "^2.2.1",
    "jquery": "^3.1.1",
    "preboot": "^4.5.2",
    "raw-loader": "^0.5.1",
    "rxjs": "5.0.3",
    "style-loader": "^0.13.0",
    "to-string-loader": "^1.1.5",
    "ts-loader": "^1.3.3",
    "typescript": "^2.0.0",
    "url-loader": "^0.5.7",
    "webpack": "^1.12.14",
    "webpack-externals-plugin": "^1.0.0",
    "webpack-hot-middleware": "^2.10.0",
    "webpack-merge": "^2.4.0",
    "zone.js": "^0.7.5"

### Current behavior
An unhandled exception occurred while processing the request.

Exception: Call to Node module failed with error: Prerendering failed because of error: TypeError: Cannot read property 'SelectorMatcher' of undefined
at Object.<anonymous> (C:\ProjectsVsTeam\ImmagineWeb\Angular2Application\Angular2Application.Web\node_modules\angular2-platform-node\__private_imports__.js:19:58)
at Module._compile (module.js:570:32)
at Object.Module._extensions..js (module.js:579:10)
at Module.load (module.js:487:32)
at tryModuleLoad (module.js:446:12)
at Function.Module._load (module.js:438:3)
at Module.require (module.js:497:17)
at require (internal/module.js:20:19)
at Object.<anonymous> (C:\ProjectsVsTeam\ImmagineWeb\Angular2Application\Angular2Application.Web\node_modules\angular2-platform-node\node-platform.js:9:28)
at Module._compile (module.js:570:32)
at Object.Module._extensions..js (module.js:579:10)
at Module.load (module.js:487:32)
at tryModuleLoad (module.js:446:12)
at Function.Module._load (module.js:438:3)
at Module.require (module.js:497:17)
Current directory is: C:\ProjectsVsTeam\ImmagineWeb\Angular2Application\Angular2Application.Web

Thanks
Pierluigi

**Comment by HappyZimmer** [comment]
I have the same problem.

**Comment by khennny** [comment]
Same problem here

**Comment by Ants24** [comment]
add  "nativescript-angular": "^1.4.1"  in package.json
